name: Bug Report
description: File a bug report to help us improve TaskHarvester
title: "[BUG] "
labels: ["type:bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the documentation
          required: true
        - label: I am using a supported system configuration
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Backend API
        - Desktop Application
        - AI Processing
        - Microsoft Graph Integration
        - Wrike Integration
        - Authentication
        - Setup/Installation
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Logs
      description: If applicable, add screenshots or log outputs to help explain your problem
      placeholder: Paste screenshots or log content here

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your system information
      placeholder: |
        - OS: [e.g. Windows 11, macOS 14.0]
        - TaskHarvester Version: [e.g. v0.1.0]
        - Python Version: [e.g. 3.11.0]
        - Node.js Version: [e.g. 18.17.0]
        - GPU: [e.g. NVIDIA RTX 4080]
        - RAM: [e.g. 32GB]
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application crashes or data loss
        - High - Major functionality broken
        - Medium - Minor functionality affected
        - Low - Cosmetic or minor issue
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here