name: Feature Request
description: Suggest a new feature for TaskHarvester
title: "[FEATURE] "
labels: ["type:feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the roadmap to see if this is already planned
          required: true
        - label: This feature aligns with TaskHarvester's core mission
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend API
        - Desktop Application
        - AI Processing
        - Microsoft Graph Integration
        - Wrike Integration
        - Authentication
        - Setup/Installation
        - New Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What user need does it address?
      placeholder: As a user, I have trouble with... because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution in detail
      placeholder: I think the best approach would be to...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be beneficial
      placeholder: |
        1. When a user...
        2. During the process of...
        3. In the scenario where...
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Target User
      description: Who would primarily benefit from this feature?
      options:
        - Individual Users
        - Small Teams (2-10 people)
        - Medium Teams (10-50 people)
        - Enterprise Users (50+ people)
        - Developers/Administrators
        - All Users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking current workflow
        - High - Would significantly improve workflow
        - Medium - Nice to have improvement
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects, dependencies, or challenges you can think of

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you interested in helping implement this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
        - label: I can help with testing this feature
        - label: I can provide detailed requirements/specifications
        - label: I can help with documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request